### ISSUE TITLE
Include git commit syntax for finishing a story

### ISSUE THREAD

**Issue by roxtar** [concourse/tracker-resource#1]
Looking at the source the tracker-resource will only deliver a story if the commit message contains "fixes #story_id" or "finishes #story_id" [1]. The README should include this information. Maybe even give the option to configure what the pattern should be.

[1]: https://github.com/concourse/tracker-resource/blob/master/out/cmd/out/main.go#L80-L81

**Comment by xoebus** [comment]
Documenting the syntax would be good but we can't choose our own because the syntax is controlled by Tracker: https://www.pivotaltracker.com/help/api?version=v5#Tracker_Updates_in_SCM_Post_Commit_Hooks.

**Comment by roxtar** [comment]
Got it. Thanks.
