### ISSUE TITLE
Ability to create a story using the tracker resource

### ISSUE THREAD

**Issue by tushar-dadlani** [concourse/tracker-resource#11]
While certain resources like bosh releases, we would like to automatically a story in our icebox to deploy something that has been recently released or to create a bug in our icebox if automatically updating pipelines fail.

**Comment by utricularian** [comment]
Hi there, just throwing my vote in on this feature as we just came across a use case this would have been useful for.

**Comment by jtarchie** [comment]
We are considering this issue dead due to inactivity. Please feel free to reopen a new issue if this is still a problem. Thanks!
