### ISSUE TITLE
Allow a single commit to complete multiple tracker issues.

### ISSUE THREAD

**Issue by cgfrost** [concourse/tracker-resource#15]
If I make a git commit with the following message it should look for both issues and if applicable deliver them.
```
[finishes #127026745]
[finishes #126433767]
```

**Comment by vito** [comment]
doesn't it already?

**Comment by cgfrost** [comment]
Not that I managed with an explicit test. Just had a look at the source code, would you expect it to deliver a chore or is it just finished features?

**Comment by vito** [comment]
Only things in "finished" state, so yeah it makes sense that it'd skip chores (which go straight to accepted). The idea is you use a different hook (i.e. GH integration) to handle the `[finishes #xxx]` tag.

**Comment by cgfrost** [comment]
OK thanks. I'll go see what that hook is doing for us. Too many integrations.
