### ISSUE TITLE
Add check and in operations for this Tracker resource

### ISSUE THREAD

**Issue by RochesterinNYC** [concourse/tracker-resource#16]
We have the use case where we want to apply some operation to potentially every tracker story that comes into a certain Tracker project.

To be more specific, whenever a Tracker story is created in the public Buildpacks Tracker project, we want to check and see if it's a story generated by gitbot for a github issue ([example](https://www.pivotaltracker.com/story/show/136142059)). If it is, and it's an issue for a buildpack repo, we want to tag the story with the appropriate buildpack label (i.e. `dotnet-core` if the issue is for the `cloudfoundry/dotnet-core-buildpack` repo.

This would be possible through things like running a job that does a similar check/update operation on all our tracker stories every hour or something, but it feels more aligned with Concourse's resource paradigm to do this on each tracker story as it comes in (new version for the tracker resource would be the trigger for a label update job).

It'd be great to have a check and in operation that checks and versions on new tracker stories.

**Comment by vito** [comment]
I agree that it should implement `in` and `check` but I'm not sure what they should do, considering how specific `out` is. I'll mark this as an enhancement for now but I do wonder if we've named this resource too generically, as it does an awfully specific thing (delivering stories based on a git repo's commits). I'd be concerned with this turning into a swiss-army knife resource when really you may want a resource for different use cases.

**Comment by RochesterinNYC** [comment]
I agree with the idea of making more specific resources. I do see resources that essentially track a single story vs. a whole tracker project being completely different.

**Comment by jtarchie** [comment]
We are considering this issue dead due to inactivity. Please feel free to reopen a new issue if this is still a problem. Thanks!
