### ISSUE TITLE
Story delivery does not adhere to Tracker documentation link

### ISSUE THREAD

**Issue by mattk-pio** [concourse/tracker-resource#20]
The Readme.md links to https://www.pivotaltracker.com/help/articles/githubs_service_hook_for_tracker/#formatting-your-commits referring to how to properly format commits for Tracker story status change. However, in the PivotalTracker.com website, the keyword `Delivers` is used, while only "completes", "completed", and "complete" are supported. "delivers" and "delivered" should both be added to match the PivotalTracker.com website documentation.

**Comment by jtarchie** [comment]
The resource is only for use of transitioning from finished to delivered. If the commit has the message `delivered` already that means that it has been delivered. The documentation on Pivotal Tracker specifies the difference in behaviour, which we follow.
