### ISSUE TITLE
Option to disable comment on delivered story

### ISSUE THREAD

**Issue by jamesjoshuahill** [concourse/tracker-resource#3]
We recently upgraded and found the comments on delivered stories noisy—in our workflow we only deliver features via Concourse—so we would like an option to disable them.

**Comment by robdimsdale** [comment]
One way to solve this could be to have the text configurable via `params` in the pipeline config, and allow empty strings. Would that work for you?

**Comment by jamesjoshuahill** [comment]
@robdimsdale So when `comment: ""` is added to the params it would disable the tracker comment? Sure, that'd work for us.

**Comment by robdimsdale** [comment]
Glad to hear it. @vito @xoebus thoughts?

**Comment by vito** [comment]
We're just gonna kill the feature instead.
